details:
  name: Dashwise Default widgets
  description: Enjoy the default built-in widgets. No need to add YAML files directly.

configuration:
  widgets:
    - name: "Glanceable Clock"
      key: "main-clock"
      template: "glanceable-clock"
      category: "Clock"
    - name: "Search Bar"
      key: "search-bar"
      template: "search-bar"
      category: "Search"
    - name: "Link View"
      key: "link-view"
      template: "link-view"
      category: "Links"
    - name: "Placeholder"
      key: "placeholder"
      template: "placeholder"
      category: "Placeholder"
    - name: "Weekly view"
      key: "calendar-week"
      template: "calendar-week"
      category: "Calendar"
    - name: "Today's date"
      key: "calendar-today"
      template: "calendar-today"
      category: "Calendar"
    - name: "Upcoming events"
      key: "calendar-upcoming"
      template: "calendar-upcoming"
      category: "Calendar"
  glanceables:
    - name: "Date"
      icon: none
      text: "${date.now}" 
    - name: "Greeting"
      icon: none
      text: "Hello"
    - name: "Local Timezone"
      icon: none
      text: "${user.current_timezone}"
    - name: "World Clock"
      properties:
        timezone: "type:tz ??? 'Europe/London'"
        location: "type:String ??? 'London'"
      icon: none
      text: "${lib.date.time(${properties.timezone})} in ${properties.location}"