details:
  name: Dashwise Default widgets
  description: Enjoy the default built-in widgets. No need to add YAML files directly.

configuration:
  widgets:
    - name: "Glanceable Clock"
      key: "main-clock"
      template: "glanceable-clock"
      category: "Clock"
    - name: "Search Bar"
      key: "search-bar"
      template: "search-bar"
      category: "Search"
    - name: "Shortcuts"
      key: "shortcuts"
      template: "columns"
      category: "Search"
      data:
        input:
          shortcutIds: []
    - name: "Link View"
      key: "link-view"
      template: "link-view"
      category: "Links"
    - name: "Latest Links"
      key: "latest-links"
      template: "latest-links"
      category: "Links"
      data:
        input:
          listId: ""
          maxItems: 8
          title: "Latest Links"
    - name: "Placeholder"
      key: "placeholder"
      template: "placeholder"
      category: "Placeholder"
    - name: "Weekly view"
      key: "calendar-week"
      template: "calendar-week"
      category: "Calendar"
    - name: "Today's date"
      key: "calendar-today"
      template: "calendar-today"
      category: "Calendar"
    - name: "Upcoming events"
      key: "calendar-upcoming"
      template: "calendar-upcoming"
      category: "Calendar"
    - name: "Latest RSS Articles"
      key: "rss-feed"
      template: "rss-feed"
      category: "News"
      data:
        input:
          feedId: "all"
          maxItems: 8
          title: "Latest Articles"
    - name: "Countdown"
      key: "countdown"
      template: "countdown"
      category: "Clock"
      data:
        input:
          date: "2026-12-31"
          display_name: "New Year"
          date_format: "yyyy-MM-dd"
    - name: "Iframe"
      key: "iframe"
      template: "iframe"
      category: "Tools"
      data:
        input:
          url: "https://www.wikipedia.org"
          min_height: 300
          max_height: 600
    - name: "Image"
      key: "image"
      template: "image"
      category: "Tools"
      data:
        input:
          url: "https://placehold.co/800x450/png"
          title: ""
          title_url: ""
          click_action: ""
          invalidate_after: "5 minutes"
          alt: "Image widget"
          max_height: 600
    - name: "Progress"
      key: "progress"
      template: "progress"
      category: "Progress"
      data:
        input:
          period:
            type: "select"
            default: "day"
            options:
              - value: "year"
                label: "Year"
              - value: "month"
                label: "Month"
              - value: "day"
                label: "Day"
              - value: "week"
                label: "Week"
  glanceables:
    - name: "Date"
      icon: none
      text: "${date.now}" 
    - name: "Greeting"
      icon: none
      text: "Hello"
    - name: "Local Timezone"
      icon: none
      text: "${user.current_timezone}"
    - name: "World Clock"
      properties:
        timezone: "type:tz ??? 'Europe/London'"
        location: "type:String ??? 'London'"
      icon: none
      text: "${lib.date.time(${properties.timezone})} in ${properties.location}"
    - name: "Progress"
      key: "progress"
      icon: none
      properties:
        period: "day"
      text: "Day: 0%"
