services:
  dashwise:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: andreasmolnardev/dashwise:aio-preview
    ports:
      - "3031:3000"
    restart: unless-stopped
    environment:
      ENVIRONMENT: production
      PB_ADMIN_EMAIL: default@dashwise.local
      PB_ADMIN_PASSWORD: DashwiseIsAwesome
      PB_URL: http://127.0.0.1:8090
      NEXT_PUBLIC_PB_URL: http://127.0.0.1:8090
      NEXT_PUBLIC_APP_URL: http://localhost:3016
      START_POCKETBASE: "true"
      PB_BINARY_PATH: /usr/local/bin/pocketbase
    volumes:
      - ./pocketbase/pb_data_old:/app/pocketbase/pb_data
