version: "3.8"

services:
  dashwise:
    image: andreasmolnardev/dashwise:stable
    ports:
      - "3016:3000"
    restart: unless-stopped
    environment:
      PB_ADMIN_EMAIL: default@dashwise.local
      PB_ADMIN_PASSWORD: DashwiseIsAwesome
      NEXT_PUBLIC_PB_URL: http://pocketbase:8090
  pocketbase:
    image: andreasmolnardev/dashwise-pb:stable
    volumes:
      - ./pocketbase:/app/pb_data
    ports:
      - "8092:8090"
    restart: unless-stopped
    environment:
      PB_ADMIN_EMAIL: default@dashwise.local
      PB_ADMIN_PASSWORD: DashwiseIsAwesome
  jobs:
    image: curlimages/curl:latest
    restart: unless-stopped
    entrypoint: >
      sh -c "while true; do
               curl -s http://dashwise:3000/api/v1/jobs;
               sleep 3600;
             done"
