services:
  nextjs:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
  pocketbase:
    container_name: pocketbase-dashwise
    image: andreasmolnardev/dashwise-pb:latest
    volumes:
      - ./pocketbase/:/app/pb_data
      - ./migrations:/pb_migrations
    ports:
      - "8092:8090"
    restart: unless-stopped
    environment:
      PB_ADMIN_EMAIL: default@dashwise.local
      PB_ADMIN_PASSWORD: DashwiseIsAwesome
