services: 
  dashwise:
    build:
      context: .
    ports:
      - "3016:3000"
    restart: unless-stopped
    env_file: ./.env

  pocketbase:
    build: ./pocketbase
    environment:
      PB_ADMIN_EMAIL: default@dashwise.local
      PB_ADMIN_PASSWORD: dashwiseIsAwesome
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/test/pb_data:/app/pb_data
      - ./pocketbase/pb_migrations:/app/pb_migrations
    restart: unless-stopped

  jobs:
    build:
     context: .
     dockerfile: jobs/Dockerfile
    ports:
        - "3001:3001"
    volumes:
      - ./jobs:/usr/src/app
      - ./dashwise-sdk:/usr/src/app/dashwise-sdk
    environment:
      PB_URL: http://pocketbase:8090
      DASHWISE_URL: http://dashwise:3000
      SEARCHITEMS_SCHEDULE: "*/10 * * * *"
      MONITORING_INDEXER_SCHEDULE: "*/10 * * * *"
      MONITORING_RUNNER_SCHEDULE: "*/1 * * * *"
      ALLOW_SSL: false
      START_POCKETBASE: "false"
      PB_ADMIN_EMAIL: default@dashwise.local
      PB_ADMIN_PASSWORD: dashwiseIsAwesome  
    restart: unless-stopped
