services:
  nextjs:
    image: node:20-alpine
    container_name: dashwise-next-live
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - dashwise-default
    command: sh -c "corepack enable && pnpm install --frozen-lockfile && pnpm build && pnpm --filter apps/web run dev"

  pocketbase:
    build: ./pocketbase
    environment:
      PB_ADMIN_EMAIL: default@dashwise.local
      PB_ADMIN_PASSWORD: dashwiseIsAwesome
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/app/pb_data
      - ./pocketbase/pb_migrations:/app/pb_migrations
    networks:
      - dashwise-default
    restart: unless-stopped

  jobs:
    build:
      context: .
      dockerfile: apps/jobs/Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    env_file:
      - ./apps/jobs/.env
    volumes:
      - ./:/app
    working_dir: /app/apps/jobs
    command: sh -c "corepack enable && pnpm install && pnpm run dev"
    networks:
      - dashwise-default

networks:
  dashwise-default: