version: "3.8"

services:
  dashwise:
    image: andreasmolnardev/dashwise:stable-arm
    ports:
      - "3016:3000"
    restart: unless-stopped
    environment:
      PB_ADMIN_EMAIL: default@dashwise.local
      PB_ADMIN_PASSWORD: DashwiseIsAwesome
      NEXT_PUBLIC_PB_URL: http://pocketbase:8090
  pocketbase:
    image: andreasmolnardev/dashwise-pb:stable-arm
    volumes:
      - ./pocketbase/pb_data_migrateme:/app/pb_data
    ports:
      - "8092:8090"
    restart: unless-stopped
    environment:
      PB_ADMIN_EMAIL: default@dashwise.local
      PB_ADMIN_PASSWORD: DashwiseIsAwesome