// DO NOT EDIT — generated by bun run generate
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type GenericObject = {
    [key: string]: unknown;
};

export type Error = {
    [key: string]: unknown;
};

export type Id = string;

export type JsonBody = GenericObject;

export type GetAppConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/appConfig';
};

export type GetAppConfigResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetAppConfigResponse = GetAppConfigResponses[keyof GetAppConfigResponses];

export type GetAppInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/appInfo';
};

export type GetAppInfoResponses = {
    /**
     * OK
     */
    200: {
        updateAvailable: boolean;
        currentAppVersion: string;
        userSignupDisabled: boolean;
    };
};

export type GetAppInfoResponse = GetAppInfoResponses[keyof GetAppInfoResponses];

export type GetAuthCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/callback';
};

export type GetAuthCallbackResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetAuthCallbackResponse = GetAuthCallbackResponses[keyof GetAuthCallbackResponses];

export type PostAuthChangePasswordData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type PostAuthChangePasswordErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type PostAuthChangePasswordError = PostAuthChangePasswordErrors[keyof PostAuthChangePasswordErrors];

export type PostAuthChangePasswordResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostAuthChangePasswordResponse = PostAuthChangePasswordResponses[keyof PostAuthChangePasswordResponses];

export type DeleteAuthDeleteAccountData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/auth/delete-account';
};

export type DeleteAuthDeleteAccountErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type DeleteAuthDeleteAccountError = DeleteAuthDeleteAccountErrors[keyof DeleteAuthDeleteAccountErrors];

export type DeleteAuthDeleteAccountResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type DeleteAuthDeleteAccountResponse = DeleteAuthDeleteAccountResponses[keyof DeleteAuthDeleteAccountResponses];

export type PostAuthLoginData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthMfaData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/auth/mfa';
};

export type PostAuthMfaErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type PostAuthMfaError = PostAuthMfaErrors[keyof PostAuthMfaErrors];

export type PostAuthMfaResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostAuthMfaResponse = PostAuthMfaResponses[keyof PostAuthMfaResponses];

export type PostAuthSignupData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type PostAuthSignupErrors = {
    /**
     * Bad Request
     */
    400: Error;
};

export type PostAuthSignupError = PostAuthSignupErrors[keyof PostAuthSignupErrors];

export type PostAuthSignupResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostAuthSignupResponse = PostAuthSignupResponses[keyof PostAuthSignupResponses];

export type GetAuthSsoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sso';
};

export type GetAuthSsoResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetAuthSsoResponse = GetAuthSsoResponses[keyof GetAuthSsoResponses];

export type PostAuthValidateAuthData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/auth/validate-auth';
};

export type PostAuthValidateAuthErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type PostAuthValidateAuthError = PostAuthValidateAuthErrors[keyof PostAuthValidateAuthErrors];

export type PostAuthValidateAuthResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostAuthValidateAuthResponse = PostAuthValidateAuthResponses[keyof PostAuthValidateAuthResponses];

export type PatchAuthUpdateUserPropertyData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/auth/update-user-property';
};

export type PatchAuthUpdateUserPropertyErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type PatchAuthUpdateUserPropertyError = PatchAuthUpdateUserPropertyErrors[keyof PatchAuthUpdateUserPropertyErrors];

export type PatchAuthUpdateUserPropertyResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PatchAuthUpdateUserPropertyResponse = PatchAuthUpdateUserPropertyResponses[keyof PatchAuthUpdateUserPropertyResponses];

export type GetIntegrationsData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        resolveEndpoints?: boolean;
    };
    url: '/integrations';
};

export type GetIntegrationsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetIntegrationsResponse = GetIntegrationsResponses[keyof GetIntegrationsResponses];

export type PostIntegrationsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/integrations';
};

export type PostIntegrationsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostIntegrationsResponse = PostIntegrationsResponses[keyof PostIntegrationsResponses];

export type PostIntegrationsTestEndpointData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/integrations/test-endpoint';
};

export type PostIntegrationsTestEndpointResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostIntegrationsTestEndpointResponse = PostIntegrationsTestEndpointResponses[keyof PostIntegrationsTestEndpointResponses];

export type GetIntegrationsWidgetPropertiesData = {
    body?: never;
    path?: never;
    query?: {
        widgetSlug?: string;
    };
    url: '/integrations/widget-properties';
};

export type GetIntegrationsWidgetPropertiesResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetIntegrationsWidgetPropertiesResponse = GetIntegrationsWidgetPropertiesResponses[keyof GetIntegrationsWidgetPropertiesResponses];

export type GetLinksCollectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/links/collections';
};

export type GetLinksCollectionsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetLinksCollectionsResponse = GetLinksCollectionsResponses[keyof GetLinksCollectionsResponses];

export type PostLinksCollectionsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/links/collections';
};

export type PostLinksCollectionsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostLinksCollectionsResponse = PostLinksCollectionsResponses[keyof PostLinksCollectionsResponses];

export type GetLinksHomeGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/links/home/groups';
};

export type GetLinksHomeGroupsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetLinksHomeGroupsResponse = GetLinksHomeGroupsResponses[keyof GetLinksHomeGroupsResponses];

export type PostLinksHomeGroupsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/links/home/groups';
};

export type PostLinksHomeGroupsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostLinksHomeGroupsResponse = PostLinksHomeGroupsResponses[keyof PostLinksHomeGroupsResponses];

export type GetLinksHomeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/links/home';
};

export type GetLinksHomeResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetLinksHomeResponse = GetLinksHomeResponses[keyof GetLinksHomeResponses];

export type GetLinksFoldersData = {
    body?: never;
    path?: never;
    query?: {
        listId?: string;
    };
    url: '/links/folders';
};

export type GetLinksFoldersResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetLinksFoldersResponse = GetLinksFoldersResponses[keyof GetLinksFoldersResponses];

export type PostLinksFoldersData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/links/folders';
};

export type PostLinksFoldersResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostLinksFoldersResponse = PostLinksFoldersResponses[keyof PostLinksFoldersResponses];

export type GetLinksItemsData = {
    body?: never;
    path?: never;
    query?: {
        listId?: string;
        folderId?: string;
    };
    url: '/links/items';
};

export type GetLinksItemsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetLinksItemsResponse = GetLinksItemsResponses[keyof GetLinksItemsResponses];

export type PostLinksItemsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/links/items';
};

export type PostLinksItemsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostLinksItemsResponse = PostLinksItemsResponses[keyof PostLinksItemsResponses];

export type DeleteLinksItemsByLinkIdData = {
    body?: JsonBody;
    path: {
        linkId: string;
    };
    query?: never;
    url: '/links/items/{linkId}';
};

export type DeleteLinksItemsByLinkIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type DeleteLinksItemsByLinkIdResponse = DeleteLinksItemsByLinkIdResponses[keyof DeleteLinksItemsByLinkIdResponses];

export type PutLinksItemsByLinkIdData = {
    body?: JsonBody;
    path: {
        linkId: string;
    };
    query?: never;
    url: '/links/items/{linkId}';
};

export type PutLinksItemsByLinkIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PutLinksItemsByLinkIdResponse = PutLinksItemsByLinkIdResponses[keyof PutLinksItemsByLinkIdResponses];

export type GetLinksTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/links/tags';
};

export type GetLinksTagsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetLinksTagsResponse = GetLinksTagsResponses[keyof GetLinksTagsResponses];

export type PostLinksTagsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/links/tags';
};

export type PostLinksTagsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostLinksTagsResponse = PostLinksTagsResponses[keyof PostLinksTagsResponses];

export type GetJobsSearchItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/jobs/searchItems';
};

export type GetJobsSearchItemsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetJobsSearchItemsResponse = GetJobsSearchItemsResponses[keyof GetJobsSearchItemsResponses];

export type GetJobsPullIconsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/jobs/pullIcons';
};

export type GetJobsPullIconsErrors = {
    /**
     * Bad Request
     */
    409: Error;
};

export type GetJobsPullIconsError = GetJobsPullIconsErrors[keyof GetJobsPullIconsErrors];

export type GetJobsPullIconsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetJobsPullIconsResponse = GetJobsPullIconsResponses[keyof GetJobsPullIconsResponses];

export type GetLocationsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
    };
    url: '/locations';
};

export type GetLocationsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetLocationsResponse = GetLocationsResponses[keyof GetLocationsResponses];

export type GetMonitoringStatusData = {
    body?: never;
    path?: never;
    query?: {
        jobId?: string;
    };
    url: '/monitoringStatus';
};

export type GetMonitoringStatusResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetMonitoringStatusResponse = GetMonitoringStatusResponses[keyof GetMonitoringStatusResponses];

export type PostMonitoringStatusData = {
    body: {
        linkId?: string;
        jobId?: string;
    };
    path?: never;
    query?: never;
    url: '/monitoringStatus';
};

export type PostMonitoringStatusErrors = {
    /**
     * Bad Request
     */
    400: Error;
};

export type PostMonitoringStatusError = PostMonitoringStatusErrors[keyof PostMonitoringStatusErrors];

export type PostMonitoringStatusResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostMonitoringStatusResponse = PostMonitoringStatusResponses[keyof PostMonitoringStatusResponses];

export type GetMonitoringSshHostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/monitoring/ssh-hosts';
};

export type GetMonitoringSshHostsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetMonitoringSshHostsResponse = GetMonitoringSshHostsResponses[keyof GetMonitoringSshHostsResponses];

export type PostMonitoringSshHostsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/monitoring/ssh-hosts';
};

export type PostMonitoringSshHostsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostMonitoringSshHostsResponse = PostMonitoringSshHostsResponses[keyof PostMonitoringSshHostsResponses];

export type DeleteMonitoringSshHostsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/monitoring/ssh-hosts/{id}';
};

export type DeleteMonitoringSshHostsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type DeleteMonitoringSshHostsByIdResponse = DeleteMonitoringSshHostsByIdResponses[keyof DeleteMonitoringSshHostsByIdResponses];

export type PutMonitoringSshHostsByIdData = {
    body?: JsonBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/monitoring/ssh-hosts/{id}';
};

export type PutMonitoringSshHostsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PutMonitoringSshHostsByIdResponse = PutMonitoringSshHostsByIdResponses[keyof PutMonitoringSshHostsByIdResponses];

export type GetMonitoringHostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/monitoring/hosts';
};

export type GetMonitoringHostsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetMonitoringHostsResponse = GetMonitoringHostsResponses[keyof GetMonitoringHostsResponses];

export type PostMonitoringHostsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/monitoring/hosts';
};

export type PostMonitoringHostsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostMonitoringHostsResponse = PostMonitoringHostsResponses[keyof PostMonitoringHostsResponses];

export type DeleteMonitoringHostsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/monitoring/hosts/{id}';
};

export type DeleteMonitoringHostsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type DeleteMonitoringHostsByIdResponse = DeleteMonitoringHostsByIdResponses[keyof DeleteMonitoringHostsByIdResponses];

export type GetMonitoringHostsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/monitoring/hosts/{id}';
};

export type GetMonitoringHostsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetMonitoringHostsByIdResponse = GetMonitoringHostsByIdResponses[keyof GetMonitoringHostsByIdResponses];

export type PutMonitoringHostsByIdData = {
    body?: JsonBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/monitoring/hosts/{id}';
};

export type PutMonitoringHostsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PutMonitoringHostsByIdResponse = PutMonitoringHostsByIdResponses[keyof PutMonitoringHostsByIdResponses];

export type GetMonitoringHostsByIdStatsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/monitoring/hosts/{id}/stats';
};

export type GetMonitoringHostsByIdStatsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetMonitoringHostsByIdStatsResponse = GetMonitoringHostsByIdStatsResponses[keyof GetMonitoringHostsByIdStatsResponses];

export type GetMonitoringHostsByIdHistoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        timestamp?: string;
    };
    url: '/monitoring/hosts/{id}/history';
};

export type GetMonitoringHostsByIdHistoryResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetMonitoringHostsByIdHistoryResponse = GetMonitoringHostsByIdHistoryResponses[keyof GetMonitoringHostsByIdHistoryResponses];

export type PostMonitoringHostsByIdRefreshData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/monitoring/hosts/{id}/refresh';
};

export type PostMonitoringHostsByIdRefreshErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type PostMonitoringHostsByIdRefreshError = PostMonitoringHostsByIdRefreshErrors[keyof PostMonitoringHostsByIdRefreshErrors];

export type PostMonitoringHostsByIdRefreshResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostMonitoringHostsByIdRefreshResponse = PostMonitoringHostsByIdRefreshResponses[keyof PostMonitoringHostsByIdRefreshResponses];

export type GetNewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/news';
};

export type GetNewsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNewsResponse = GetNewsResponses[keyof GetNewsResponses];

export type GetNewsFeedData = {
    body?: never;
    path?: never;
    query?: {
        feedId?: string;
        limit?: number;
        offset?: number;
    };
    url: '/news/feed';
};

export type GetNewsFeedResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNewsFeedResponse = GetNewsFeedResponses[keyof GetNewsFeedResponses];

export type GetNewsFeedRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/news/feed-refresh';
};

export type GetNewsFeedRefreshResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNewsFeedRefreshResponse = GetNewsFeedRefreshResponses[keyof GetNewsFeedRefreshResponses];

export type PostNewsFeedRefreshData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/news/feed-refresh';
};

export type PostNewsFeedRefreshResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNewsFeedRefreshResponse = PostNewsFeedRefreshResponses[keyof PostNewsFeedRefreshResponses];

export type PostNewsFeedSubscribeData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/news/feed-subscribe';
};

export type PostNewsFeedSubscribeResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNewsFeedSubscribeResponse = PostNewsFeedSubscribeResponses[keyof PostNewsFeedSubscribeResponses];

export type PostNewsFeedUnsubscribeData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/news/feed-unsubscribe';
};

export type PostNewsFeedUnsubscribeResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNewsFeedUnsubscribeResponse = PostNewsFeedUnsubscribeResponses[keyof PostNewsFeedUnsubscribeResponses];

export type PostNewsFeedUpdateData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/news/feed-update';
};

export type PostNewsFeedUpdateResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNewsFeedUpdateResponse = PostNewsFeedUpdateResponses[keyof PostNewsFeedUpdateResponses];

export type GetNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        unread?: boolean;
        count?: boolean;
    };
    url: '/notifications';
};

export type GetNotificationsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNotificationsResponse = GetNotificationsResponses[keyof GetNotificationsResponses];

export type PostNotificationsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications';
};

export type PostNotificationsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNotificationsResponse = PostNotificationsResponses[keyof PostNotificationsResponses];

export type DeleteNotificationsForwardersData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications/forwarders';
};

export type DeleteNotificationsForwardersResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type DeleteNotificationsForwardersResponse = DeleteNotificationsForwardersResponses[keyof DeleteNotificationsForwardersResponses];

export type GetNotificationsForwardersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/forwarders';
};

export type GetNotificationsForwardersResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNotificationsForwardersResponse = GetNotificationsForwardersResponses[keyof GetNotificationsForwardersResponses];

export type PostNotificationsForwardersData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications/forwarders';
};

export type PostNotificationsForwardersResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNotificationsForwardersResponse = PostNotificationsForwardersResponses[keyof PostNotificationsForwardersResponses];

export type PutNotificationsForwardersData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications/forwarders';
};

export type PutNotificationsForwardersResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PutNotificationsForwardersResponse = PutNotificationsForwardersResponses[keyof PutNotificationsForwardersResponses];

export type PostNotificationsForwardersTestData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications/forwarders/test';
};

export type PostNotificationsForwardersTestResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNotificationsForwardersTestResponse = PostNotificationsForwardersTestResponses[keyof PostNotificationsForwardersTestResponses];

export type PostNotificationsMarkAsReadData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications/markAsRead';
};

export type PostNotificationsMarkAsReadResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNotificationsMarkAsReadResponse = PostNotificationsMarkAsReadResponses[keyof PostNotificationsMarkAsReadResponses];

export type PostNotificationsByTopicData = {
    body?: JsonBody;
    path: {
        topic: string;
    };
    query?: never;
    url: '/notifications/{topic}';
};

export type PostNotificationsByTopicResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNotificationsByTopicResponse = PostNotificationsByTopicResponses[keyof PostNotificationsByTopicResponses];

export type DeleteNotificationsTopicsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications/topics';
};

export type DeleteNotificationsTopicsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type DeleteNotificationsTopicsResponse = DeleteNotificationsTopicsResponses[keyof DeleteNotificationsTopicsResponses];

export type GetNotificationsTopicsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/topics';
};

export type GetNotificationsTopicsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNotificationsTopicsResponse = GetNotificationsTopicsResponses[keyof GetNotificationsTopicsResponses];

export type PostNotificationsTopicsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications/topics';
};

export type PostNotificationsTopicsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNotificationsTopicsResponse = PostNotificationsTopicsResponses[keyof PostNotificationsTopicsResponses];

export type DeleteNotificationsTopicTokensData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications/topicTokens';
};

export type DeleteNotificationsTopicTokensResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type DeleteNotificationsTopicTokensResponse = DeleteNotificationsTopicTokensResponses[keyof DeleteNotificationsTopicTokensResponses];

export type GetNotificationsTopicTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/topicTokens';
};

export type GetNotificationsTopicTokensResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNotificationsTopicTokensResponse = GetNotificationsTopicTokensResponses[keyof GetNotificationsTopicTokensResponses];

export type PostNotificationsTopicTokensData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications/topicTokens';
};

export type PostNotificationsTopicTokensResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNotificationsTopicTokensResponse = PostNotificationsTopicTokensResponses[keyof PostNotificationsTopicTokensResponses];

export type PutNotificationsTopicTokensData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications/topicTokens';
};

export type PutNotificationsTopicTokensResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PutNotificationsTopicTokensResponse = PutNotificationsTopicTokensResponses[keyof PutNotificationsTopicTokensResponses];

export type GetSearchItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/searchItems';
};

export type GetSearchItemsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetSearchItemsResponse = GetSearchItemsResponses[keyof GetSearchItemsResponses];

export type GetPageConfigData = {
    body?: never;
    path?: never;
    query?: {
        pageName?: string;
    };
    url: '/pageConfig';
};

export type GetPageConfigResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetPageConfigResponse = GetPageConfigResponses[keyof GetPageConfigResponses];

export type PutPageConfigData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/pageConfig';
};

export type PutPageConfigResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PutPageConfigResponse = PutPageConfigResponses[keyof PutPageConfigResponses];

export type GetPageConfigUserPagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pageConfig/user-pages';
};

export type GetPageConfigUserPagesResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetPageConfigUserPagesResponse = GetPageConfigUserPagesResponses[keyof GetPageConfigUserPagesResponses];

export type GetTestBookmarksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test/bookmarks';
};

export type GetTestBookmarksResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetTestBookmarksResponse = GetTestBookmarksResponses[keyof GetTestBookmarksResponses];

export type GetWallpapersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wallpapers';
};

export type GetWallpapersResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetWallpapersResponse = GetWallpapersResponses[keyof GetWallpapersResponses];

export type PostWallpapersData = {
    body: {
        contentBase64: string;
        fileName?: string;
        mimeType?: string;
        convertToWebp?: boolean;
        auth?: {
            token?: string;
        };
    };
    path?: never;
    query?: never;
    url: '/wallpapers';
};

export type PostWallpapersResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostWallpapersResponse = PostWallpapersResponses[keyof PostWallpapersResponses];

export type GetWidgetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/widgets';
};

export type GetWidgetsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetWidgetsResponse = GetWidgetsResponses[keyof GetWidgetsResponses];

export type GetWidgetsGlanceableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/widgets/glanceable';
};

export type GetWidgetsGlanceableResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetWidgetsGlanceableResponse = GetWidgetsGlanceableResponses[keyof GetWidgetsGlanceableResponses];

export type GetWidgetsGlanceablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/widgets/glanceables';
};

export type GetWidgetsGlanceablesResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetWidgetsGlanceablesResponse = GetWidgetsGlanceablesResponses[keyof GetWidgetsGlanceablesResponses];

export type GetWeatherData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/weather';
};

export type GetWeatherResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetWeatherResponse = GetWeatherResponses[keyof GetWeatherResponses];

export type PostPageConfigHomeData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/pageConfig/home';
};

export type PostPageConfigHomeResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostPageConfigHomeResponse = PostPageConfigHomeResponses[keyof PostPageConfigHomeResponses];

export type PostPageConfigMigrateLegacyData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/pageConfig/migrate-legacy';
};

export type PostPageConfigMigrateLegacyResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostPageConfigMigrateLegacyResponse = PostPageConfigMigrateLegacyResponses[keyof PostPageConfigMigrateLegacyResponses];

export type PostPageConfigIntegrationDataData = {
    body?: JsonBody;
    path?: never;
    query?: {
        page?: string;
    };
    url: '/pageConfig/integrationData';
};

export type PostPageConfigIntegrationDataResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostPageConfigIntegrationDataResponse = PostPageConfigIntegrationDataResponses[keyof PostPageConfigIntegrationDataResponses];

export type PutLinksCollectionsByCollectionIdData = {
    body?: JsonBody;
    path: {
        collectionId: string;
    };
    query?: never;
    url: '/links/collections/{collectionId}';
};

export type PutLinksCollectionsByCollectionIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PutLinksCollectionsByCollectionIdResponse = PutLinksCollectionsByCollectionIdResponses[keyof PutLinksCollectionsByCollectionIdResponses];

export type PutLinksFoldersByFolderIdIconData = {
    body?: JsonBody;
    path: {
        folderId: string;
    };
    query?: never;
    url: '/links/folders/{folderId}/icon';
};

export type PutLinksFoldersByFolderIdIconResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PutLinksFoldersByFolderIdIconResponse = PutLinksFoldersByFolderIdIconResponses[keyof PutLinksFoldersByFolderIdIconResponses];

export type PutLinksTagsByTagIdData = {
    body?: JsonBody;
    path: {
        tagId: string;
    };
    query?: never;
    url: '/links/tags/{tagId}';
};

export type PutLinksTagsByTagIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PutLinksTagsByTagIdResponse = PutLinksTagsByTagIdResponses[keyof PutLinksTagsByTagIdResponses];

export type PostLinksReorderData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/links/reorder';
};

export type PostLinksReorderResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostLinksReorderResponse = PostLinksReorderResponses[keyof PostLinksReorderResponses];

export type GetGlanceablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/glanceables';
};

export type GetGlanceablesResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetGlanceablesResponse = GetGlanceablesResponses[keyof GetGlanceablesResponses];

export type GetWidgetsByIntegrationData = {
    body?: never;
    path?: never;
    query?: {
        widgetKey?: string;
    };
    url: '/widgets/by-integration';
};

export type GetWidgetsByIntegrationResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetWidgetsByIntegrationResponse = GetWidgetsByIntegrationResponses[keyof GetWidgetsByIntegrationResponses];

export type GetGlanceablesByIntegrationData = {
    body?: never;
    path?: never;
    query?: {
        glanceableType?: string;
    };
    url: '/glanceables/by-integration';
};

export type GetGlanceablesByIntegrationResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetGlanceablesByIntegrationResponse = GetGlanceablesByIntegrationResponses[keyof GetGlanceablesByIntegrationResponses];

export type DeleteIntegrationsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/integrations/{id}';
};

export type DeleteIntegrationsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type DeleteIntegrationsByIdResponse = DeleteIntegrationsByIdResponses[keyof DeleteIntegrationsByIdResponses];

export type PutIntegrationsByIdData = {
    body?: JsonBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/integrations/{id}';
};

export type PutIntegrationsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PutIntegrationsByIdResponse = PutIntegrationsByIdResponses[keyof PutIntegrationsByIdResponses];

export type GetIntegrationsConsumerDataData = {
    body?: never;
    path?: never;
    query?: {
        type?: string;
        key?: string;
        input?: string;
    };
    url: '/integrations/consumerData';
};

export type GetIntegrationsConsumerDataResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetIntegrationsConsumerDataResponse = GetIntegrationsConsumerDataResponses[keyof GetIntegrationsConsumerDataResponses];

export type PostIntegrationsConsumerDataData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/integrations/consumerData';
};

export type PostIntegrationsConsumerDataResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostIntegrationsConsumerDataResponse = PostIntegrationsConsumerDataResponses[keyof PostIntegrationsConsumerDataResponses];

export type GetIntegrationsCaldavEventsData = {
    body?: never;
    path?: never;
    query?: {
        integrationId?: string;
    };
    url: '/integrations/caldav/events';
};

export type GetIntegrationsCaldavEventsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetIntegrationsCaldavEventsResponse = GetIntegrationsCaldavEventsResponses[keyof GetIntegrationsCaldavEventsResponses];

export type PostIntegrationsProxyActionData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/integrations/proxyAction';
};

export type PostIntegrationsProxyActionResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostIntegrationsProxyActionResponse = PostIntegrationsProxyActionResponses[keyof PostIntegrationsProxyActionResponses];

export type GetMonitorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/monitors';
};

export type GetMonitorsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetMonitorsResponse = GetMonitorsResponses[keyof GetMonitorsResponses];

export type PostMonitorsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/monitors';
};

export type PostMonitorsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostMonitorsResponse = PostMonitorsResponses[keyof PostMonitorsResponses];

export type DeleteMonitorsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/monitors/{id}';
};

export type DeleteMonitorsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type DeleteMonitorsByIdResponse = DeleteMonitorsByIdResponses[keyof DeleteMonitorsByIdResponses];

export type GetMonitorsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/monitors/{id}';
};

export type GetMonitorsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetMonitorsByIdResponse = GetMonitorsByIdResponses[keyof GetMonitorsByIdResponses];

export type PutMonitorsByIdData = {
    body?: JsonBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/monitors/{id}';
};

export type PutMonitorsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PutMonitorsByIdResponse = PutMonitorsByIdResponses[keyof PutMonitorsByIdResponses];

export type GetNewsFeedsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/news/feeds/{id}';
};

export type GetNewsFeedsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNewsFeedsByIdResponse = GetNewsFeedsByIdResponses[keyof GetNewsFeedsByIdResponses];

export type GetNewsFeedRecordsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/news/feed-records/{id}';
};

export type GetNewsFeedRecordsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNewsFeedRecordsByIdResponse = GetNewsFeedRecordsByIdResponses[keyof GetNewsFeedRecordsByIdResponses];

export type PostNewsFeedRecordsByIdData = {
    body?: JsonBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/news/feed-records/{id}';
};

export type PostNewsFeedRecordsByIdResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNewsFeedRecordsByIdResponse = PostNewsFeedRecordsByIdResponses[keyof PostNewsFeedRecordsByIdResponses];

export type PostNewsFeedRecordsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/news/feed-records';
};

export type PostNewsFeedRecordsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNewsFeedRecordsResponse = PostNewsFeedRecordsResponses[keyof PostNewsFeedRecordsResponses];

export type GetNewsFeedMetadataData = {
    body?: never;
    path?: never;
    query?: {
        url?: string;
    };
    url: '/news/feed-metadata';
};

export type GetNewsFeedMetadataResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNewsFeedMetadataResponse = GetNewsFeedMetadataResponses[keyof GetNewsFeedMetadataResponses];

export type GetNewsSubscriptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/news/subscriptions';
};

export type GetNewsSubscriptionsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNewsSubscriptionsResponse = GetNewsSubscriptionsResponses[keyof GetNewsSubscriptionsResponses];

export type GetNewsSubscriptionsByIdJsonData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/news/subscriptions/{id}/json';
};

export type GetNewsSubscriptionsByIdJsonResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNewsSubscriptionsByIdJsonResponse = GetNewsSubscriptionsByIdJsonResponses[keyof GetNewsSubscriptionsByIdJsonResponses];

export type GetNewsFeedsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/news/feeds';
};

export type GetNewsFeedsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetNewsFeedsResponse = GetNewsFeedsResponses[keyof GetNewsFeedsResponses];

export type PostNewsFixMissingTitlesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/news/fix-missing-titles';
};

export type PostNewsFixMissingTitlesResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNewsFixMissingTitlesResponse = PostNewsFixMissingTitlesResponses[keyof PostNewsFixMissingTitlesResponses];

export type PostNotificationsTestData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/notifications/test';
};

export type PostNotificationsTestResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostNotificationsTestResponse = PostNotificationsTestResponses[keyof PostNotificationsTestResponses];

export type GetSearchItemsFrequentlyUsedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/searchItems/frequentlyUsed';
};

export type GetSearchItemsFrequentlyUsedResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type GetSearchItemsFrequentlyUsedResponse = GetSearchItemsFrequentlyUsedResponses[keyof GetSearchItemsFrequentlyUsedResponses];

export type PostSearchItemsUsageStatsData = {
    body?: JsonBody;
    path?: never;
    query?: never;
    url: '/searchItems/usageStats';
};

export type PostSearchItemsUsageStatsResponses = {
    /**
     * OK
     */
    200: GenericObject;
};

export type PostSearchItemsUsageStatsResponse = PostSearchItemsUsageStatsResponses[keyof PostSearchItemsUsageStatsResponses];
