/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedPageRouteImport } from './routes/_authenticated.$page'
import { Route as AuthenticatedFrameRouteImport } from './routes/_authenticated.frame'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated.links'
import { Route as AuthenticatedMigrateRouteImport } from './routes/_authenticated.migrate'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated.news'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthenticatedAppsMonitoringRouteImport } from './routes/_authenticated.apps.monitoring'
import { Route as AuthenticatedAppsNewsRouteImport } from './routes/_authenticated.apps.news'
import { Route as AuthenticatedLinksIndexRouteImport } from './routes/_authenticated.links.index'
import { Route as AuthenticatedLinksHomeRouteImport } from './routes/_authenticated.links.home'
import { Route as AuthenticatedLinksListsRouteImport } from './routes/_authenticated.links.lists'
import { Route as AuthenticatedLinksTagsRouteImport } from './routes/_authenticated.links.tags'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated.notifications.index'
import { Route as AuthenticatedNotificationsInboxRouteImport } from './routes/_authenticated.notifications.inbox'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated.settings.account'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated.settings.appearance'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated.settings.general'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated.settings.integrations'
import { Route as AuthenticatedSettingsPagesRouteImport } from './routes/_authenticated.settings.pages'
import { Route as AuthenticatedSettingsScreensaverRouteImport } from './routes/_authenticated.settings.screensaver'
import { Route as AuthenticatedSettingsSearchRouteImport } from './routes/_authenticated.settings.search'
import { Route as AuthenticatedAppsMonitoringIndexRouteImport } from './routes/_authenticated.apps.monitoring.index'
import { Route as AuthenticatedAppsMonitoringMonitorIdRouteImport } from './routes/_authenticated.apps.monitoring.$monitorId'
import { Route as AuthenticatedAppsMonitoringNotificationsRouteImport } from './routes/_authenticated.apps.monitoring.notifications'
import { Route as AuthenticatedAppsMonitoringSshRouteImport } from './routes/_authenticated.apps.monitoring.ssh'
import { Route as AuthenticatedAppsNewsIndexRouteImport } from './routes/_authenticated.apps.news.index'
import { Route as AuthenticatedAppsNewsFeedIdRouteImport } from './routes/_authenticated.apps.news.$feedId'
import { Route as AuthenticatedLinksListsListIdRouteImport } from './routes/_authenticated.links.lists.$listId'
import { Route as AuthenticatedLinksTagsTagIdRouteImport } from './routes/_authenticated.links.tags.$tagId'
import { Route as AuthenticatedAppsMonitoringHostsHostIdRouteImport } from './routes/_authenticated.apps.monitoring.hosts.$hostId'
import { Route as AuthenticatedAppsMonitoringSshHostIdRouteImport } from './routes/_authenticated.apps.monitoring.ssh.$hostId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPageRoute = AuthenticatedPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFrameRoute = AuthenticatedFrameRouteImport.update({
  id: '/frame',
  path: '/frame',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMigrateRoute = AuthenticatedMigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/app/$',
  path: '/app/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAppsMonitoringRoute =
  AuthenticatedAppsMonitoringRouteImport.update({
    id: '/apps/monitoring',
    path: '/apps/monitoring',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsNewsRoute = AuthenticatedAppsNewsRouteImport.update({
  id: '/apps/news',
  path: '/apps/news',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLinksIndexRoute = AuthenticatedLinksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLinksRoute,
} as any)
const AuthenticatedLinksHomeRoute = AuthenticatedLinksHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedLinksRoute,
} as any)
const AuthenticatedLinksListsRoute = AuthenticatedLinksListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AuthenticatedLinksRoute,
} as any)
const AuthenticatedLinksTagsRoute = AuthenticatedLinksTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedLinksRoute,
} as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNotificationsRoute,
  } as any)
const AuthenticatedNotificationsInboxRoute =
  AuthenticatedNotificationsInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedNotificationsRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPagesRoute =
  AuthenticatedSettingsPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsScreensaverRoute =
  AuthenticatedSettingsScreensaverRouteImport.update({
    id: '/screensaver',
    path: '/screensaver',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSearchRoute =
  AuthenticatedSettingsSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedAppsMonitoringIndexRoute =
  AuthenticatedAppsMonitoringIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppsMonitoringRoute,
  } as any)
const AuthenticatedAppsMonitoringMonitorIdRoute =
  AuthenticatedAppsMonitoringMonitorIdRouteImport.update({
    id: '/$monitorId',
    path: '/$monitorId',
    getParentRoute: () => AuthenticatedAppsMonitoringRoute,
  } as any)
const AuthenticatedAppsMonitoringNotificationsRoute =
  AuthenticatedAppsMonitoringNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppsMonitoringRoute,
  } as any)
const AuthenticatedAppsMonitoringSshRoute =
  AuthenticatedAppsMonitoringSshRouteImport.update({
    id: '/ssh',
    path: '/ssh',
    getParentRoute: () => AuthenticatedAppsMonitoringRoute,
  } as any)
const AuthenticatedAppsNewsIndexRoute =
  AuthenticatedAppsNewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppsNewsRoute,
  } as any)
const AuthenticatedAppsNewsFeedIdRoute =
  AuthenticatedAppsNewsFeedIdRouteImport.update({
    id: '/$feedId',
    path: '/$feedId',
    getParentRoute: () => AuthenticatedAppsNewsRoute,
  } as any)
const AuthenticatedLinksListsListIdRoute =
  AuthenticatedLinksListsListIdRouteImport.update({
    id: '/$listId',
    path: '/$listId',
    getParentRoute: () => AuthenticatedLinksListsRoute,
  } as any)
const AuthenticatedLinksTagsTagIdRoute =
  AuthenticatedLinksTagsTagIdRouteImport.update({
    id: '/$tagId',
    path: '/$tagId',
    getParentRoute: () => AuthenticatedLinksTagsRoute,
  } as any)
const AuthenticatedAppsMonitoringHostsHostIdRoute =
  AuthenticatedAppsMonitoringHostsHostIdRouteImport.update({
    id: '/hosts/$hostId',
    path: '/hosts/$hostId',
    getParentRoute: () => AuthenticatedAppsMonitoringRoute,
  } as any)
const AuthenticatedAppsMonitoringSshHostIdRoute =
  AuthenticatedAppsMonitoringSshHostIdRouteImport.update({
    id: '/$hostId',
    path: '/$hostId',
    getParentRoute: () => AuthenticatedAppsMonitoringSshRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/$page': typeof AuthenticatedPageRoute
  '/frame': typeof AuthenticatedFrameRoute
  '/home': typeof AuthenticatedHomeRoute
  '/links': typeof AuthenticatedLinksRouteWithChildren
  '/migrate': typeof AuthenticatedMigrateRoute
  '/news': typeof AuthenticatedNewsRoute
  '/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/apps/monitoring': typeof AuthenticatedAppsMonitoringRouteWithChildren
  '/apps/news': typeof AuthenticatedAppsNewsRouteWithChildren
  '/links/home': typeof AuthenticatedLinksHomeRoute
  '/links/lists': typeof AuthenticatedLinksListsRouteWithChildren
  '/links/tags': typeof AuthenticatedLinksTagsRouteWithChildren
  '/notifications/inbox': typeof AuthenticatedNotificationsInboxRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/pages': typeof AuthenticatedSettingsPagesRoute
  '/settings/screensaver': typeof AuthenticatedSettingsScreensaverRoute
  '/settings/search': typeof AuthenticatedSettingsSearchRoute
  '/links/': typeof AuthenticatedLinksIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/apps/monitoring/$monitorId': typeof AuthenticatedAppsMonitoringMonitorIdRoute
  '/apps/monitoring/notifications': typeof AuthenticatedAppsMonitoringNotificationsRoute
  '/apps/monitoring/ssh': typeof AuthenticatedAppsMonitoringSshRouteWithChildren
  '/apps/news/$feedId': typeof AuthenticatedAppsNewsFeedIdRoute
  '/links/lists/$listId': typeof AuthenticatedLinksListsListIdRoute
  '/links/tags/$tagId': typeof AuthenticatedLinksTagsTagIdRoute
  '/apps/monitoring/': typeof AuthenticatedAppsMonitoringIndexRoute
  '/apps/news/': typeof AuthenticatedAppsNewsIndexRoute
  '/apps/monitoring/hosts/$hostId': typeof AuthenticatedAppsMonitoringHostsHostIdRoute
  '/apps/monitoring/ssh/$hostId': typeof AuthenticatedAppsMonitoringSshHostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$page': typeof AuthenticatedPageRoute
  '/frame': typeof AuthenticatedFrameRoute
  '/home': typeof AuthenticatedHomeRoute
  '/migrate': typeof AuthenticatedMigrateRoute
  '/news': typeof AuthenticatedNewsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/$': typeof AppSplatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth': typeof AuthIndexRoute
  '/links/home': typeof AuthenticatedLinksHomeRoute
  '/links/lists': typeof AuthenticatedLinksListsRouteWithChildren
  '/links/tags': typeof AuthenticatedLinksTagsRouteWithChildren
  '/notifications/inbox': typeof AuthenticatedNotificationsInboxRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/pages': typeof AuthenticatedSettingsPagesRoute
  '/settings/screensaver': typeof AuthenticatedSettingsScreensaverRoute
  '/settings/search': typeof AuthenticatedSettingsSearchRoute
  '/links': typeof AuthenticatedLinksIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/apps/monitoring/$monitorId': typeof AuthenticatedAppsMonitoringMonitorIdRoute
  '/apps/monitoring/notifications': typeof AuthenticatedAppsMonitoringNotificationsRoute
  '/apps/monitoring/ssh': typeof AuthenticatedAppsMonitoringSshRouteWithChildren
  '/apps/news/$feedId': typeof AuthenticatedAppsNewsFeedIdRoute
  '/links/lists/$listId': typeof AuthenticatedLinksListsListIdRoute
  '/links/tags/$tagId': typeof AuthenticatedLinksTagsTagIdRoute
  '/apps/monitoring': typeof AuthenticatedAppsMonitoringIndexRoute
  '/apps/news': typeof AuthenticatedAppsNewsIndexRoute
  '/apps/monitoring/hosts/$hostId': typeof AuthenticatedAppsMonitoringHostsHostIdRoute
  '/apps/monitoring/ssh/$hostId': typeof AuthenticatedAppsMonitoringSshHostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/$page': typeof AuthenticatedPageRoute
  '/_authenticated/frame': typeof AuthenticatedFrameRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/links': typeof AuthenticatedLinksRouteWithChildren
  '/_authenticated/migrate': typeof AuthenticatedMigrateRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/app/$': typeof AppSplatRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/apps/monitoring': typeof AuthenticatedAppsMonitoringRouteWithChildren
  '/_authenticated/apps/news': typeof AuthenticatedAppsNewsRouteWithChildren
  '/_authenticated/links/home': typeof AuthenticatedLinksHomeRoute
  '/_authenticated/links/lists': typeof AuthenticatedLinksListsRouteWithChildren
  '/_authenticated/links/tags': typeof AuthenticatedLinksTagsRouteWithChildren
  '/_authenticated/notifications/inbox': typeof AuthenticatedNotificationsInboxRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/pages': typeof AuthenticatedSettingsPagesRoute
  '/_authenticated/settings/screensaver': typeof AuthenticatedSettingsScreensaverRoute
  '/_authenticated/settings/search': typeof AuthenticatedSettingsSearchRoute
  '/_authenticated/links/': typeof AuthenticatedLinksIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/apps/monitoring/$monitorId': typeof AuthenticatedAppsMonitoringMonitorIdRoute
  '/_authenticated/apps/monitoring/notifications': typeof AuthenticatedAppsMonitoringNotificationsRoute
  '/_authenticated/apps/monitoring/ssh': typeof AuthenticatedAppsMonitoringSshRouteWithChildren
  '/_authenticated/apps/news/$feedId': typeof AuthenticatedAppsNewsFeedIdRoute
  '/_authenticated/links/lists/$listId': typeof AuthenticatedLinksListsListIdRoute
  '/_authenticated/links/tags/$tagId': typeof AuthenticatedLinksTagsTagIdRoute
  '/_authenticated/apps/monitoring/': typeof AuthenticatedAppsMonitoringIndexRoute
  '/_authenticated/apps/news/': typeof AuthenticatedAppsNewsIndexRoute
  '/_authenticated/apps/monitoring/hosts/$hostId': typeof AuthenticatedAppsMonitoringHostsHostIdRoute
  '/_authenticated/apps/monitoring/ssh/$hostId': typeof AuthenticatedAppsMonitoringSshHostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/$page'
    | '/frame'
    | '/home'
    | '/links'
    | '/migrate'
    | '/news'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/app/$'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/'
    | '/apps/monitoring'
    | '/apps/news'
    | '/links/home'
    | '/links/lists'
    | '/links/tags'
    | '/notifications/inbox'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/pages'
    | '/settings/screensaver'
    | '/settings/search'
    | '/links/'
    | '/notifications/'
    | '/settings/'
    | '/apps/monitoring/$monitorId'
    | '/apps/monitoring/notifications'
    | '/apps/monitoring/ssh'
    | '/apps/news/$feedId'
    | '/links/lists/$listId'
    | '/links/tags/$tagId'
    | '/apps/monitoring/'
    | '/apps/news/'
    | '/apps/monitoring/hosts/$hostId'
    | '/apps/monitoring/ssh/$hostId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$page'
    | '/frame'
    | '/home'
    | '/migrate'
    | '/news'
    | '/onboarding'
    | '/app/$'
    | '/auth/login'
    | '/auth/signup'
    | '/auth'
    | '/links/home'
    | '/links/lists'
    | '/links/tags'
    | '/notifications/inbox'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/pages'
    | '/settings/screensaver'
    | '/settings/search'
    | '/links'
    | '/notifications'
    | '/settings'
    | '/apps/monitoring/$monitorId'
    | '/apps/monitoring/notifications'
    | '/apps/monitoring/ssh'
    | '/apps/news/$feedId'
    | '/links/lists/$listId'
    | '/links/tags/$tagId'
    | '/apps/monitoring'
    | '/apps/news'
    | '/apps/monitoring/hosts/$hostId'
    | '/apps/monitoring/ssh/$hostId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/$page'
    | '/_authenticated/frame'
    | '/_authenticated/home'
    | '/_authenticated/links'
    | '/_authenticated/migrate'
    | '/_authenticated/news'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/app/$'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/'
    | '/_authenticated/apps/monitoring'
    | '/_authenticated/apps/news'
    | '/_authenticated/links/home'
    | '/_authenticated/links/lists'
    | '/_authenticated/links/tags'
    | '/_authenticated/notifications/inbox'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/pages'
    | '/_authenticated/settings/screensaver'
    | '/_authenticated/settings/search'
    | '/_authenticated/links/'
    | '/_authenticated/notifications/'
    | '/_authenticated/settings/'
    | '/_authenticated/apps/monitoring/$monitorId'
    | '/_authenticated/apps/monitoring/notifications'
    | '/_authenticated/apps/monitoring/ssh'
    | '/_authenticated/apps/news/$feedId'
    | '/_authenticated/links/lists/$listId'
    | '/_authenticated/links/tags/$tagId'
    | '/_authenticated/apps/monitoring/'
    | '/_authenticated/apps/news/'
    | '/_authenticated/apps/monitoring/hosts/$hostId'
    | '/_authenticated/apps/monitoring/ssh/$hostId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AppSplatRoute: typeof AppSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$page': {
      id: '/_authenticated/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof AuthenticatedPageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/frame': {
      id: '/_authenticated/frame'
      path: '/frame'
      fullPath: '/frame'
      preLoaderRoute: typeof AuthenticatedFrameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/migrate': {
      id: '/_authenticated/migrate'
      path: '/migrate'
      fullPath: '/migrate'
      preLoaderRoute: typeof AuthenticatedMigrateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/app/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/apps/monitoring': {
      id: '/_authenticated/apps/monitoring'
      path: '/apps/monitoring'
      fullPath: '/apps/monitoring'
      preLoaderRoute: typeof AuthenticatedAppsMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/news': {
      id: '/_authenticated/apps/news'
      path: '/apps/news'
      fullPath: '/apps/news'
      preLoaderRoute: typeof AuthenticatedAppsNewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/links/': {
      id: '/_authenticated/links/'
      path: '/'
      fullPath: '/links/'
      preLoaderRoute: typeof AuthenticatedLinksIndexRouteImport
      parentRoute: typeof AuthenticatedLinksRoute
    }
    '/_authenticated/links/home': {
      id: '/_authenticated/links/home'
      path: '/home'
      fullPath: '/links/home'
      preLoaderRoute: typeof AuthenticatedLinksHomeRouteImport
      parentRoute: typeof AuthenticatedLinksRoute
    }
    '/_authenticated/links/lists': {
      id: '/_authenticated/links/lists'
      path: '/lists'
      fullPath: '/links/lists'
      preLoaderRoute: typeof AuthenticatedLinksListsRouteImport
      parentRoute: typeof AuthenticatedLinksRoute
    }
    '/_authenticated/links/tags': {
      id: '/_authenticated/links/tags'
      path: '/tags'
      fullPath: '/links/tags'
      preLoaderRoute: typeof AuthenticatedLinksTagsRouteImport
      parentRoute: typeof AuthenticatedLinksRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedNotificationsRoute
    }
    '/_authenticated/notifications/inbox': {
      id: '/_authenticated/notifications/inbox'
      path: '/inbox'
      fullPath: '/notifications/inbox'
      preLoaderRoute: typeof AuthenticatedNotificationsInboxRouteImport
      parentRoute: typeof AuthenticatedNotificationsRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/pages': {
      id: '/_authenticated/settings/pages'
      path: '/pages'
      fullPath: '/settings/pages'
      preLoaderRoute: typeof AuthenticatedSettingsPagesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/screensaver': {
      id: '/_authenticated/settings/screensaver'
      path: '/screensaver'
      fullPath: '/settings/screensaver'
      preLoaderRoute: typeof AuthenticatedSettingsScreensaverRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/search': {
      id: '/_authenticated/settings/search'
      path: '/search'
      fullPath: '/settings/search'
      preLoaderRoute: typeof AuthenticatedSettingsSearchRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/apps/monitoring/': {
      id: '/_authenticated/apps/monitoring/'
      path: '/'
      fullPath: '/apps/monitoring/'
      preLoaderRoute: typeof AuthenticatedAppsMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedAppsMonitoringRoute
    }
    '/_authenticated/apps/monitoring/$monitorId': {
      id: '/_authenticated/apps/monitoring/$monitorId'
      path: '/$monitorId'
      fullPath: '/apps/monitoring/$monitorId'
      preLoaderRoute: typeof AuthenticatedAppsMonitoringMonitorIdRouteImport
      parentRoute: typeof AuthenticatedAppsMonitoringRoute
    }
    '/_authenticated/apps/monitoring/notifications': {
      id: '/_authenticated/apps/monitoring/notifications'
      path: '/notifications'
      fullPath: '/apps/monitoring/notifications'
      preLoaderRoute: typeof AuthenticatedAppsMonitoringNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppsMonitoringRoute
    }
    '/_authenticated/apps/monitoring/ssh': {
      id: '/_authenticated/apps/monitoring/ssh'
      path: '/ssh'
      fullPath: '/apps/monitoring/ssh'
      preLoaderRoute: typeof AuthenticatedAppsMonitoringSshRouteImport
      parentRoute: typeof AuthenticatedAppsMonitoringRoute
    }
    '/_authenticated/apps/news/': {
      id: '/_authenticated/apps/news/'
      path: '/'
      fullPath: '/apps/news/'
      preLoaderRoute: typeof AuthenticatedAppsNewsIndexRouteImport
      parentRoute: typeof AuthenticatedAppsNewsRoute
    }
    '/_authenticated/apps/news/$feedId': {
      id: '/_authenticated/apps/news/$feedId'
      path: '/$feedId'
      fullPath: '/apps/news/$feedId'
      preLoaderRoute: typeof AuthenticatedAppsNewsFeedIdRouteImport
      parentRoute: typeof AuthenticatedAppsNewsRoute
    }
    '/_authenticated/links/lists/$listId': {
      id: '/_authenticated/links/lists/$listId'
      path: '/$listId'
      fullPath: '/links/lists/$listId'
      preLoaderRoute: typeof AuthenticatedLinksListsListIdRouteImport
      parentRoute: typeof AuthenticatedLinksListsRoute
    }
    '/_authenticated/links/tags/$tagId': {
      id: '/_authenticated/links/tags/$tagId'
      path: '/$tagId'
      fullPath: '/links/tags/$tagId'
      preLoaderRoute: typeof AuthenticatedLinksTagsTagIdRouteImport
      parentRoute: typeof AuthenticatedLinksTagsRoute
    }
    '/_authenticated/apps/monitoring/hosts/$hostId': {
      id: '/_authenticated/apps/monitoring/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/apps/monitoring/hosts/$hostId'
      preLoaderRoute: typeof AuthenticatedAppsMonitoringHostsHostIdRouteImport
      parentRoute: typeof AuthenticatedAppsMonitoringRoute
    }
    '/_authenticated/apps/monitoring/ssh/$hostId': {
      id: '/_authenticated/apps/monitoring/ssh/$hostId'
      path: '/$hostId'
      fullPath: '/apps/monitoring/ssh/$hostId'
      preLoaderRoute: typeof AuthenticatedAppsMonitoringSshHostIdRouteImport
      parentRoute: typeof AuthenticatedAppsMonitoringSshRoute
    }
  }
}

interface AuthenticatedLinksListsRouteChildren {
  AuthenticatedLinksListsListIdRoute: typeof AuthenticatedLinksListsListIdRoute
}

const AuthenticatedLinksListsRouteChildren: AuthenticatedLinksListsRouteChildren =
  {
    AuthenticatedLinksListsListIdRoute: AuthenticatedLinksListsListIdRoute,
  }

const AuthenticatedLinksListsRouteWithChildren =
  AuthenticatedLinksListsRoute._addFileChildren(
    AuthenticatedLinksListsRouteChildren,
  )

interface AuthenticatedLinksTagsRouteChildren {
  AuthenticatedLinksTagsTagIdRoute: typeof AuthenticatedLinksTagsTagIdRoute
}

const AuthenticatedLinksTagsRouteChildren: AuthenticatedLinksTagsRouteChildren =
  {
    AuthenticatedLinksTagsTagIdRoute: AuthenticatedLinksTagsTagIdRoute,
  }

const AuthenticatedLinksTagsRouteWithChildren =
  AuthenticatedLinksTagsRoute._addFileChildren(
    AuthenticatedLinksTagsRouteChildren,
  )

interface AuthenticatedLinksRouteChildren {
  AuthenticatedLinksHomeRoute: typeof AuthenticatedLinksHomeRoute
  AuthenticatedLinksListsRoute: typeof AuthenticatedLinksListsRouteWithChildren
  AuthenticatedLinksTagsRoute: typeof AuthenticatedLinksTagsRouteWithChildren
  AuthenticatedLinksIndexRoute: typeof AuthenticatedLinksIndexRoute
}

const AuthenticatedLinksRouteChildren: AuthenticatedLinksRouteChildren = {
  AuthenticatedLinksHomeRoute: AuthenticatedLinksHomeRoute,
  AuthenticatedLinksListsRoute: AuthenticatedLinksListsRouteWithChildren,
  AuthenticatedLinksTagsRoute: AuthenticatedLinksTagsRouteWithChildren,
  AuthenticatedLinksIndexRoute: AuthenticatedLinksIndexRoute,
}

const AuthenticatedLinksRouteWithChildren =
  AuthenticatedLinksRoute._addFileChildren(AuthenticatedLinksRouteChildren)

interface AuthenticatedNotificationsRouteChildren {
  AuthenticatedNotificationsInboxRoute: typeof AuthenticatedNotificationsInboxRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
}

const AuthenticatedNotificationsRouteChildren: AuthenticatedNotificationsRouteChildren =
  {
    AuthenticatedNotificationsInboxRoute: AuthenticatedNotificationsInboxRoute,
    AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  }

const AuthenticatedNotificationsRouteWithChildren =
  AuthenticatedNotificationsRoute._addFileChildren(
    AuthenticatedNotificationsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsPagesRoute: typeof AuthenticatedSettingsPagesRoute
  AuthenticatedSettingsScreensaverRoute: typeof AuthenticatedSettingsScreensaverRoute
  AuthenticatedSettingsSearchRoute: typeof AuthenticatedSettingsSearchRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsPagesRoute: AuthenticatedSettingsPagesRoute,
  AuthenticatedSettingsScreensaverRoute: AuthenticatedSettingsScreensaverRoute,
  AuthenticatedSettingsSearchRoute: AuthenticatedSettingsSearchRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedAppsMonitoringSshRouteChildren {
  AuthenticatedAppsMonitoringSshHostIdRoute: typeof AuthenticatedAppsMonitoringSshHostIdRoute
}

const AuthenticatedAppsMonitoringSshRouteChildren: AuthenticatedAppsMonitoringSshRouteChildren =
  {
    AuthenticatedAppsMonitoringSshHostIdRoute:
      AuthenticatedAppsMonitoringSshHostIdRoute,
  }

const AuthenticatedAppsMonitoringSshRouteWithChildren =
  AuthenticatedAppsMonitoringSshRoute._addFileChildren(
    AuthenticatedAppsMonitoringSshRouteChildren,
  )

interface AuthenticatedAppsMonitoringRouteChildren {
  AuthenticatedAppsMonitoringMonitorIdRoute: typeof AuthenticatedAppsMonitoringMonitorIdRoute
  AuthenticatedAppsMonitoringNotificationsRoute: typeof AuthenticatedAppsMonitoringNotificationsRoute
  AuthenticatedAppsMonitoringSshRoute: typeof AuthenticatedAppsMonitoringSshRouteWithChildren
  AuthenticatedAppsMonitoringIndexRoute: typeof AuthenticatedAppsMonitoringIndexRoute
  AuthenticatedAppsMonitoringHostsHostIdRoute: typeof AuthenticatedAppsMonitoringHostsHostIdRoute
}

const AuthenticatedAppsMonitoringRouteChildren: AuthenticatedAppsMonitoringRouteChildren =
  {
    AuthenticatedAppsMonitoringMonitorIdRoute:
      AuthenticatedAppsMonitoringMonitorIdRoute,
    AuthenticatedAppsMonitoringNotificationsRoute:
      AuthenticatedAppsMonitoringNotificationsRoute,
    AuthenticatedAppsMonitoringSshRoute:
      AuthenticatedAppsMonitoringSshRouteWithChildren,
    AuthenticatedAppsMonitoringIndexRoute:
      AuthenticatedAppsMonitoringIndexRoute,
    AuthenticatedAppsMonitoringHostsHostIdRoute:
      AuthenticatedAppsMonitoringHostsHostIdRoute,
  }

const AuthenticatedAppsMonitoringRouteWithChildren =
  AuthenticatedAppsMonitoringRoute._addFileChildren(
    AuthenticatedAppsMonitoringRouteChildren,
  )

interface AuthenticatedAppsNewsRouteChildren {
  AuthenticatedAppsNewsFeedIdRoute: typeof AuthenticatedAppsNewsFeedIdRoute
  AuthenticatedAppsNewsIndexRoute: typeof AuthenticatedAppsNewsIndexRoute
}

const AuthenticatedAppsNewsRouteChildren: AuthenticatedAppsNewsRouteChildren = {
  AuthenticatedAppsNewsFeedIdRoute: AuthenticatedAppsNewsFeedIdRoute,
  AuthenticatedAppsNewsIndexRoute: AuthenticatedAppsNewsIndexRoute,
}

const AuthenticatedAppsNewsRouteWithChildren =
  AuthenticatedAppsNewsRoute._addFileChildren(
    AuthenticatedAppsNewsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPageRoute: typeof AuthenticatedPageRoute
  AuthenticatedFrameRoute: typeof AuthenticatedFrameRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRouteWithChildren
  AuthenticatedMigrateRoute: typeof AuthenticatedMigrateRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedAppsMonitoringRoute: typeof AuthenticatedAppsMonitoringRouteWithChildren
  AuthenticatedAppsNewsRoute: typeof AuthenticatedAppsNewsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPageRoute: AuthenticatedPageRoute,
  AuthenticatedFrameRoute: AuthenticatedFrameRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRouteWithChildren,
  AuthenticatedMigrateRoute: AuthenticatedMigrateRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedAppsMonitoringRoute:
    AuthenticatedAppsMonitoringRouteWithChildren,
  AuthenticatedAppsNewsRoute: AuthenticatedAppsNewsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AppSplatRoute: AppSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
