/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        cascadeDelete: true,
        collectionId: "_pb_users_auth_",
        hidden: false,
        id: "relation9812647350",
        maxSelect: 1,
        minSelect: 1,
        name: "owner",
        presentable: false,
        required: true,
        system: false,
        type: "relation",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text5681247390",
        max: 120,
        min: 1,
        name: "source",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text1740382569",
        max: 200,
        min: 0,
        name: "sourceId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text2684019573",
        max: 256,
        min: 0,
        name: "eventId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text7836140259",
        max: 256,
        min: 0,
        name: "idempotencyKey",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text4297613805",
        max: 200,
        min: 1,
        name: "type",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text6502391748",
        max: 240,
        min: 1,
        name: "title",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text9418302756",
        max: 2000,
        min: 0,
        name: "description",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "select5381047296",
        maxSelect: 1,
        name: "severity",
        presentable: false,
        required: true,
        system: false,
        type: "select",
        values: ["info", "success", "warning", "error"],
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text2097541836",
        max: 40,
        min: 20,
        name: "occurredAt",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "json8642031759",
        maxSize: 16384,
        name: "metadata",
        presentable: false,
        required: false,
        system: false,
        type: "json",
      },
      {
        hidden: false,
        id: "json3175902468",
        maxSize: 2048,
        name: "action",
        presentable: false,
        required: false,
        system: false,
        type: "json",
      },
      {
        hidden: false,
        id: "autodate1527493086",
        name: "createdAt",
        onCreate: true,
        onUpdate: false,
        presentable: false,
        system: false,
        type: "autodate",
      },
    ],
    id: "pbc_activity001",
    indexes: [
      "CREATE INDEX idx_activities_owner_occurred_at ON activities (owner, occurredAt DESC)",
      "CREATE UNIQUE INDEX idx_activities_owner_source_instance_idempotency ON activities (owner, source, sourceId, idempotencyKey) WHERE idempotencyKey != ''",
    ],
    listRule: null,
    name: "activities",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_activity001");
  return app.delete(collection);
});
