import YAML from "yaml";

import {
  appConfigContract,
  appInfoContract,
} from "../apps/backend/src/features/system/system.contract";
import type { GetContract } from "../apps/backend/src/lib/http/contract";

const sourcePath = new URL("../apps/backend/openapi.yaml", import.meta.url);
const beginMarker = "  # BEGIN GENERATED SYSTEM CONTRACTS";
const endMarker = "  # END GENERATED SYSTEM CONTRACTS";

function zodToOpenApiSchema(schema: any): Record<string, unknown> {
  const typeName = schema?._def?.typeName;

  switch (typeName) {
    case "ZodString":
      return { type: "string" };
    case "ZodBoolean":
      return { type: "boolean" };
    case "ZodNumber":
      return { type: "number" };
    case "ZodUnknown":
    case "ZodAny":
      return {};
    case "ZodRecord":
      return {
        type: "object",
        additionalProperties: zodToOpenApiSchema(schema._def.valueType),
      };
    case "ZodObject": {
      const shape = schema._def.shape();
      return {
        type: "object",
        properties: Object.fromEntries(
          Object.entries(shape).map(([key, value]) => [key, zodToOpenApiSchema(value)]),
        ),
        required: Object.keys(shape),
        additionalProperties: schema._def.unknownKeys === "passthrough",
      };
    }
    default:
      throw new Error(`Unsupported Zod type in OpenAPI adapter: ${typeName}`);
  }
}

function toOpenApiPath(contract: GetContract<any>) {
  return {
    get: {
      tags: contract.tags,
      summary: contract.summary,
      responses: {
        "200": {
          description: "OK",
          content: {
            "application/json": {
              schema: zodToOpenApiSchema(contract.response),
            },
          },
        },
      },
    },
  };
}

const generatedPaths = {
  "/appConfig": toOpenApiPath(appConfigContract),
  "/appInfo": toOpenApiPath(appInfoContract),
};
const pathsYaml = YAML.stringify(generatedPaths)
  .trimEnd()
  .split("\n")
  .map((line) => `  ${line}`)
  .join("\n");
const generatedBlock = [
  "  # DO NOT EDIT — generated by bun run generate from system.contract.ts",
  beginMarker,
  pathsYaml,
  endMarker,
].join("\n");

const source = await Bun.file(sourcePath).text();
const generatedBlockPattern = / {2}# DO NOT EDIT — (?: {2}# DO NOT EDIT — )*generated by bun run generate from system\.contract\.ts\n {2}# BEGIN GENERATED SYSTEM CONTRACTS[\s\S]*?\n {2}# END GENERATED SYSTEM CONTRACTS/;

if (!generatedBlockPattern.test(source)) {
  throw new Error("OpenAPI generated-system-contract markers are missing or malformed.");
}

await Bun.write(
  sourcePath,
  source.replace(generatedBlockPattern, generatedBlock),
);
