import { readdir } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const header = "// DO NOT EDIT — generated by bun run generate\n";
const generatedTypeScriptPaths = [
  resolve(root, "packages/api-types/src/openapi.ts"),
];

async function collectTypeScriptFiles(directory: string): Promise<void> {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) {
      await collectTypeScriptFiles(path);
    } else if (entry.isFile() && entry.name.endsWith(".ts")) {
      generatedTypeScriptPaths.push(path);
    }
  }
}

await collectTypeScriptFiles(resolve(root, "apps/web/src/lib/api"));

for (const path of generatedTypeScriptPaths) {
  const file = Bun.file(path);
  const contents = await file.text();
  const marked = contents.startsWith(header) ? contents : `${header}${contents}`;

  if (marked !== contents) {
    await Bun.write(path, marked);
  }
}
